version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      no_cache: true
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src 
    environment:
      - DB_HOST=db
      - DB_NAME=steampunk_construction
      - DB_USER=steam_user
      - DB_PASSWORD=gear_pass
    depends_on:
      - db
    networks:
      - steampunk_network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: steampunk_construction
      MYSQL_USER: steam_user
      MYSQL_PASSWORD: gear_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - steampunk_network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - steampunk_network

networks:
  steampunk_network:
    driver: bridge

volumes:
  db_data: